<?php
class ControllerCommonLanguage extends Controller {
	public function index() {
		$this->load->language('common/language');
		$this->load->model('localisation/language');

		$data['action'] = $this->url->link('common/language/language', '', $this->isSecure());
		$data['code'] = $this->session->data['language'];
		$data['languages'] = array();

		$language_url = new LanguageUrl($this->registry);
		$target = $language_url->getCurrentTarget();

		$redirect_data = array(
			'route'    => $target['route'],
			'params'   => $target['args'],
			'protocol' => $this->isSecure()
		);

		$redirect = base64_encode(json_encode($redirect_data));
		$data['redirect'] = $redirect;

		$results = $this->model_localisation_language->getLanguages();

		foreach ($results as $result) {
			if (!$result['status']) {
				continue;
			}

			$language_id = (int)$result['language_id'];
			$href = $language_url->link(
				$target['route'],
				$target['args'],
				$language_id,
				$this->isSecure()
			);

			$switch_url = $this->url->link(
				'common/language/switchLanguage',
				array(
					'language_id' => $language_id,
					'redirect'    => $redirect
				),
				$this->isSecure()
			);

			$data['languages'][] = array(
				'language_id' => $language_id,
				'name'        => $result['name'],
				'code'        => $result['code'],
				'href'        => $href,
				'switch_url'  => $switch_url
			);
		}

		return $this->load->view('common/language', $data);
	}

	public function language() {
		$this->load->model('localisation/language');

		$languages = $this->model_localisation_language->getLanguages();
		$code = '';

		if (isset($this->request->post['code']) && is_scalar($this->request->post['code'])) {
			$code = (string)$this->request->post['code'];

			if (!isset($languages[$code]) || empty($languages[$code]['status'])) {
				$code = '';
			}
		}

		if ($code !== '') {
			$this->applyLanguage($languages[$code]);
		}

		$this->redirectToTarget(
			isset($this->request->post['redirect']) ? $this->request->post['redirect'] : ''
		);
	}

	/**
	 * Theme-friendly language switch endpoint.
	 *
	 * Themes can link directly to this route instead of constructing SEO paths.
	 * The language_id is validated and the final page URL is generated by the
	 * same rewrite stack used by the rest of the store.
	 */
	public function switchLanguage() {
		$this->load->model('localisation/language');

		$languages = $this->model_localisation_language->getLanguages();
		$language_id = isset($this->request->get['language_id'])
			? (int)$this->request->get['language_id']
			: 0;

		foreach ($languages as $language) {
			if (
				!empty($language['status'])
				&& (int)$language['language_id'] === $language_id
			) {
				$this->applyLanguage($language);
				break;
			}
		}

		$this->redirectToTarget(
			isset($this->request->get['redirect']) ? $this->request->get['redirect'] : ''
		);
	}

	private function redirectToTarget($encoded_redirect) {
		$redirect_data = $this->decodeRedirect($encoded_redirect);

		$route = isset($redirect_data['route']) ? $redirect_data['route'] : 'common/home';
		$params = isset($redirect_data['params']) ? $redirect_data['params'] : array();

		// Backward compatibility with redirect payloads generated before the
		// LanguageUrl refactor, where params were stored as a query string.
		if (!is_array($params) && !is_string($params)) {
			$params = array();
		}
		$protocol = isset($redirect_data['protocol'])
			? (bool)$redirect_data['protocol']
			: $this->isSecure();

		if (!is_string($route) || !preg_match('/^[a-zA-Z0-9_\/]+$/', $route)) {
			$route = 'common/home';
			$params = array();
		}

		$this->response->redirect($this->url->link($route, $params, $protocol));
	}

	private function decodeRedirect($encoded_redirect) {
		if (!is_string($encoded_redirect) || $encoded_redirect === '') {
			return array();
		}

		$decoded = base64_decode($encoded_redirect, true);

		if ($decoded === false) {
			return array();
		}

		$data = json_decode($decoded, true);

		return is_array($data) ? $data : array();
	}

	private function applyLanguage($language) {
		if (
			!is_array($language)
			|| empty($language['code'])
			|| empty($language['language_id'])
		) {
			return;
		}

		$code = (string)$language['code'];
		$language_id = (int)$language['language_id'];

		$this->session->data['language'] = $code;
		$this->config->set('config_language_id', $language_id);

		$language_object = new Language($code);
		$language_object->load($code);
		$this->registry->set('language', $language_object);

		setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/');
	}

	private function isSecure() {
		return (
			!empty($this->request->server['HTTPS'])
			&& strtolower((string)$this->request->server['HTTPS']) !== 'off'
		);
	}
}
